// Auto-generated by scripts/update-version.js on every build/dev launch
export const APP_INFO = {
  name: 'KhataKithab',
  version: 'v0.3.10',
  rawVersion: '0.3.10',
  isDev: true,
  isBeta: false,
  stage: 'Local Dev',
  build: '2026.08.23.2147',
  versionFull: 'khatakithab v0.3.10 (Local Dev Build 2026.08.23.2147)',
  description: 'Smart Personal Finance & Group Expense Splitting App',
  developer: 'You & Antigravity (Pair Programming)',
  techStack: 'Next.js 15 • TypeScript • Tailwind CSS • Firebase Engine'
};
