// Auto-generated by scripts/update-version.js on every build/dev launch
export const APP_INFO = {
  name: 'KhataKithab',
  version: 'v0.1.0-beta.1',
  rawVersion: '0.1.0-beta.1',
  isBeta: true,
  stage: 'Beta',
  build: '2026.08.22.1919',
  versionFull: 'khatakithab v0.1.0-beta.1 (Beta Build 2026.08.22.1919)',
  description: 'Smart Personal Finance & Group Expense Splitting App',
  developer: 'You & Antigravity (Pair Programming)',
  techStack: 'Next.js 15 • TypeScript • Tailwind CSS • Firebase Engine'
};
