// Auto-generated by scripts/update-version.js on every build/dev launch
export const APP_INFO = {
  name: 'KhataKithab',
  version: 'v0.4.0-beta.2',
  rawVersion: '0.4.0-beta.2',
  isDev: true,
  isBeta: true,
  stage: 'Local Dev',
  build: '2026.08.24.1038',
  versionFull: 'khatakithab v0.4.0-beta.2 (Local Dev Build 2026.08.24.1038)',
  description: 'Smart Personal Finance & Group Expense Splitting App',
  developer: 'You & Antigravity (Pair Programming)',
  techStack: 'Next.js 15 • TypeScript • Tailwind CSS • Firebase Engine'
};
