const fs = require('fs');
const path = require('path');

const packageJsonPath = path.join(__dirname, '..', 'package.json');
const constantsPath = path.join(__dirname, '..', 'src', 'lib', 'constants.ts');

const pkg = JSON.parse(fs.readFileSync(packageJsonPath, 'utf8'));

// Detect branch from Netlify environment (process.env.BRANCH) or local git
let localGitBranch = '';
try {
  localGitBranch = require('child_process').execSync('git rev-parse --abbrev-ref HEAD', { encoding: 'utf8' }).trim().toLowerCase();
} catch (e) {}

const isNetlifyBuild = Boolean(process.env.NETLIFY || process.env.BUILD_ID);
const isDev = process.argv.includes('--dev') || !isNetlifyBuild;
const netlifyBranch = (process.env.BRANCH || localGitBranch || '').toLowerCase();
const appEnv = (process.env.NEXT_PUBLIC_APP_ENV || '').toLowerCase();
const isProdBranch =
  netlifyBranch === 'main' ||
  netlifyBranch === 'prod' ||
  netlifyBranch === 'production' ||
  appEnv === 'production';

// Auto-increment build version only when explicit --bump is passed
const shouldBump = process.argv.includes('--bump');

if (shouldBump) {
  let [versionCore, betaTag] = pkg.version.split('-beta.');
  let [major, minor, patch] = versionCore.split('.').map(Number);
  let betaNum = betaTag ? parseInt(betaTag, 10) : 0;

  if (isProdBranch) {
    // On production branch, strip beta tag and bump patch if it had a beta tag
    if (betaTag) {
      pkg.version = `${major}.${minor}.${patch}`;
    } else {
      patch += 1;
      pkg.version = `${major}.${minor}.${patch}`;
    }
  } else {
    // On beta or development branch
    if (betaTag) {
      betaNum += 1;
      pkg.version = `${major}.${minor}.${patch}-beta.${betaNum}`;
    } else {
      pkg.version = `${major}.${minor}.${patch}-beta.1`;
    }
  }

  fs.writeFileSync(packageJsonPath, JSON.stringify(pkg, null, 2) + '\n', 'utf8');
}

// Format current build timestamp (e.g. 2026.08.22.1226)
const now = new Date();
const pad = (n) => String(n).padStart(2, '0');
const buildTimestamp = `${now.getFullYear()}.${pad(now.getMonth() + 1)}.${pad(now.getDate())}.${pad(now.getHours())}${pad(now.getMinutes())}`;

const versionString = `v${pkg.version}`;
const isBeta = !isProdBranch && (pkg.version.includes('beta') || appEnv === 'beta');
const stage = isDev && !isNetlifyBuild ? 'Local Dev' : isBeta ? 'Beta Flight' : 'Production';

const constantsContent = `// Auto-generated by scripts/update-version.js on every build/dev launch
export const APP_INFO = {
  name: 'KhataKithab',
  version: '${versionString}',
  rawVersion: '${pkg.version}',
  isDev: ${isDev && !isNetlifyBuild},
  isBeta: ${isBeta},
  stage: '${stage}',
  build: '${buildTimestamp}',
  versionFull: '${pkg.name} ${versionString} (${stage} Build ${buildTimestamp})',
  description: 'Smart Personal Finance & Group Expense Splitting App',
  developer: 'You & Antigravity (Pair Programming)',
  techStack: 'Next.js 15 • TypeScript • Tailwind CSS • Firebase Engine'
};
`;

fs.writeFileSync(constantsPath, constantsContent, 'utf8');

// Ensure current build entry is recorded in changelog-data.json
try {
  const changelogDataPath = path.join(__dirname, '..', 'src', 'lib', 'changelog-data.json');
  if (fs.existsSync(changelogDataPath)) {
    const changelogData = JSON.parse(fs.readFileSync(changelogDataPath, 'utf8'));
    const targetKey = isDev && !isNetlifyBuild ? 'dev' : isBeta ? 'beta' : 'prod';

    if (!changelogData[targetKey]) changelogData[targetKey] = [];

    const existingIndex = changelogData[targetKey].findIndex((item) => item.version === versionString);
    const todayStr = `${now.getFullYear()}-${pad(now.getMonth() + 1)}-${pad(now.getDate())}`;

    if (existingIndex === -1) {
      const newEntry = {
        version: versionString,
        stage: stage,
        date: todayStr,
        title: `${stage} Build ${versionString}`,
        summary: `Automated build record created on ${todayStr} at ${buildTimestamp}.`,
        isCurrent: true,
        highlights: [
          '⚡ Minor performance improvements and optimizations.',
          '🛡️ Improved stability and overall app performance.',
          '✨ Minor UI/UX refinements.',
          '🐛 Bug fixes and internal improvements.'
        ],
        features: [
          {
            title: 'Performance & UX Refinements',
            description: 'Minor performance improvements, UI/UX refinements, and stability optimizations.',
            tag: 'Improved'
          }
        ],
        fixes: [
          'Minor performance improvements and optimizations.',
          'Improved stability and overall app performance.',
          'Minor UI/UX refinements.',
          'Bug fixes and internal improvements.'
        ]
      };
      changelogData[targetKey] = [newEntry, ...changelogData[targetKey].map((c) => ({ ...c, isCurrent: false }))];
      fs.writeFileSync(changelogDataPath, JSON.stringify(changelogData, null, 2) + '\n', 'utf8');
    }
  }
} catch (e) {}

console.log(`[KhataKithab Build] Version set to ${versionString} (${buildTimestamp}) [Stage: ${stage}]`);



