const fs = require('fs');
const path = require('path');

const packageJsonPath = path.join(__dirname, '..', 'package.json');
const constantsPath = path.join(__dirname, '..', 'src', 'lib', 'constants.ts');

const pkg = JSON.parse(fs.readFileSync(packageJsonPath, 'utf8'));

// Detect branch from Netlify environment (process.env.BRANCH) or custom env
const netlifyBranch = (process.env.BRANCH || '').toLowerCase();
const appEnv = (process.env.NEXT_PUBLIC_APP_ENV || '').toLowerCase();
const isProdBranch =
  netlifyBranch === 'main' ||
  netlifyBranch === 'prod' ||
  netlifyBranch === 'production' ||
  appEnv === 'production';

// Auto-increment build version unless --no-bump is passed
const shouldBump = !process.argv.includes('--no-bump');

if (shouldBump) {
  let [versionCore, betaTag] = pkg.version.split('-beta.');
  let [major, minor, patch] = versionCore.split('.').map(Number);
  let betaNum = betaTag ? parseInt(betaTag, 10) : 0;

  if (isProdBranch) {
    // On production branch, strip beta tag and bump patch if it had a beta tag
    if (betaTag) {
      pkg.version = `${major}.${minor}.${patch}`;
    } else {
      patch += 1;
      pkg.version = `${major}.${minor}.${patch}`;
    }
  } else {
    // On beta or development branch
    if (betaTag) {
      betaNum += 1;
      pkg.version = `${major}.${minor}.${patch}-beta.${betaNum}`;
    } else {
      pkg.version = `${major}.${minor}.${patch}-beta.1`;
    }
  }

  fs.writeFileSync(packageJsonPath, JSON.stringify(pkg, null, 2) + '\n', 'utf8');
}

// Format current build timestamp (e.g. 2026.08.22.1226)
const now = new Date();
const pad = (n) => String(n).padStart(2, '0');
const buildTimestamp = `${now.getFullYear()}.${pad(now.getMonth() + 1)}.${pad(now.getDate())}.${pad(now.getHours())}${pad(now.getMinutes())}`;

const versionString = `v${pkg.version}`;
const isBeta = !isProdBranch && (pkg.version.includes('beta') || appEnv === 'beta');

const constantsContent = `// Auto-generated by scripts/update-version.js on every build/dev launch
export const APP_INFO = {
  name: 'KhataKithab',
  version: '${versionString}',
  rawVersion: '${pkg.version}',
  isBeta: ${isBeta},
  stage: '${isBeta ? 'Beta Flight' : 'Production'}',
  build: '${buildTimestamp}',
  versionFull: '${pkg.name} ${versionString} (${isBeta ? 'Beta Flight Build' : 'Release Build'} ${buildTimestamp})',
  description: 'Smart Personal Finance & Group Expense Splitting App',
  developer: 'You & Antigravity (Pair Programming)',
  techStack: 'Next.js 15 • TypeScript • Tailwind CSS • Firebase Engine'
};
`;

fs.writeFileSync(constantsPath, constantsContent, 'utf8');
console.log(`[KhataKithab Build] Version set to ${versionString} (${buildTimestamp}) [Stage: ${isBeta ? 'Beta Flight' : 'Production'}]`);

