const fs = require('fs');
const path = require('path');

const packageJsonPath = path.join(__dirname, '..', 'package.json');
const constantsPath = path.join(__dirname, '..', 'src', 'lib', 'constants.ts');

const pkg = JSON.parse(fs.readFileSync(packageJsonPath, 'utf8'));

// Format current build timestamp (e.g. 2026.08.22.1226)
const now = new Date();
const pad = (n) => String(n).padStart(2, '0');
const buildTimestamp = `${now.getFullYear()}.${pad(now.getMonth() + 1)}.${pad(now.getDate())}.${pad(now.getHours())}${pad(now.getMinutes())}`;

const versionString = `v${pkg.version}`;
const isBeta = pkg.version.includes('beta');

const constantsContent = `// Auto-generated by scripts/update-version.js on every build/dev launch
export const APP_INFO = {
  name: 'Rupee Khata',
  version: '${versionString}',
  rawVersion: '${pkg.version}',
  isBeta: ${isBeta},
  stage: '${isBeta ? 'Beta' : 'Stable'}',
  build: '${buildTimestamp}',
  versionFull: '${pkg.name} ${versionString} (${isBeta ? 'Beta Build' : 'Build'} ${buildTimestamp})',
  description: 'Smart Personal Finance & Group Expense Splitting App',
  developer: 'You & Antigravity (Pair Programming)',
  techStack: 'Next.js 15 • TypeScript • Tailwind CSS • Firebase Engine'
};
`;

fs.writeFileSync(constantsPath, constantsContent, 'utf8');
console.log(`[Rupee Khata Build] Updated version constants to ${versionString} (${buildTimestamp})`);
